@Api_HostAddress = http://localhost:5296

### listar usuarios
GET {{Api_HostAddress}}/users/
Accept: application/json

### ver un usuario
GET {{Api_HostAddress}}/users/827fb15f-a8bb-4645-a045-6b82187a1f24/details
Accept: application/json

### agregar un usuario
POST {{Api_HostAddress}}/users/
Content-Type: application/json
Accept: application/json

{
  "role":2,
  "name": "Yudy Polgar",
  "email": "polgar@ejemplo.com"
}

### mdificar el nombre de un usuario
PUT {{Api_HostAddress}}/users/update-name
Content-Type: application/json
Accept: application/json

{
  "id": "7cad3f76-b704-4524-a1d9-451a3c087670",
  "name": "GMI YUDY POLGAR"
}

### eliminar un usuario
DELETE {{Api_HostAddress}}/users/1c95bdcf-9904-4642-b4b2-35e49805174d
Accept: application/json

### agregar tarea
POST {{Api_HostAddress}}/assignments/
Content-Type: application/json
Accept: application/json

{
  "AssignedToId":"827fb15f-a8bb-4645-a045-6b82187a1f24",
  "title": "Cambio en la interfaz",
  "description": "mejora en la interfaz de tareas",
  "dueAt": "2026-05-12"
}

### ver una tarea
GET {{Api_HostAddress}}/assignments/468c6d12-7532-4980-bb58-3978af4afc0d/details
Accept: application/json

### listado de tareas
GET {{Api_HostAddress}}/assignments/
Accept: application/json

### listado de tareas por usuario
GET {{Api_HostAddress}}/assignments/user/827fb15f-a8bb-4645-a045-6b82187a1f24
Accept: application/json