@Api_HostAddress = http://localhost:5296

### listar usuarios
GET {{Api_HostAddress}}/users/
Accept: application/json

### ver un usuario
GET {{Api_HostAddress}}/users/827fb15f-a8bb-4645-a045-6b82187a1f24/details
Accept: application/json

### agregar un usuario
POST {{Api_HostAddress}}/users/
Content-Type: application/json
Accept: application/json

{
  "role":2,
  "name": "Darth Vader",
  "email": "dv@ejemplo.com"
}

### mdificar el nombre de un usuario
PUT {{Api_HostAddress}}/users/update-name
Content-Type: application/json
Accept: application/json

{
  "id": "1c95bdcf-9904-4642-b4b2-35e49805174d",
  "name": "Anakin Skywalker"
}

### eliminar un usuario
DELETE {{Api_HostAddress}}/users/1c95bdcf-9904-4642-b4b2-35e49805174d
Accept: application/json

### agregar tarea
POST {{Api_HostAddress}}/assignments/
Content-Type: application/json
Accept: application/json

{
  "AssignedToId":"47ccf05d-38a9-4a00-b31f-60e0eb98fb7c",
  "title": "Task de demostracion",
  "description": "primer task",
  "dueAt": "2026-05-22"
}
